### ISSUE TITLE
Stencils?

### ISSUE THREAD

**Issue by aaronkorver** [confluentinc/event-streaming-patterns#255]
Hey, great work on the pattern repository.  I find the iconography used to be extremely clean and was wondering if you have open-sourced just those stencils of the individual items for others to use in their docs?

Something similar to https://support.microsoft.com/en-us/office/create-azure-diagrams-in-visio-efbb25e7-c80e-42e1-b1ad-7ef630ff01b7 for example

**Comment by ybyzek** [comment]
@aaronkorver here's some of the iconography (though looks like some of the icons used in the pattern diagrams are not present): https://assets.confluent.io/web/361c83f3f8557809/collection--confluent-icons-2021

**Comment by aaronkorver** [comment]
Nice! I appreciate https://assets.confluent.io/web/361c83f3f8557809/collection--confluent-icons-2021/?mediaId=D2D9F9A1-BB4E-4FC9-B0C14C95CE820C8A as Machine Learning :-)
