### ISSUE TITLE
Definition of Events/Commands/Messages is contrary to commonly accepted definition

### ISSUE THREAD

**Issue by WadeWaldron** [confluentinc/event-streaming-patterns#261]
https://github.com/confluentinc/event-streaming-patterns/blob/15ca13177fb5bb0078561756b7a2d4f4f9a00f71/site/event/command-event.html#L240

This section of the document states:

> Events often fall into one of two categories: messages and commands.

The more commonly accepted definition would be that:

> Messages fall into one of two categories: commands and events

For example:

https://event-driven.io/en/whats_the_difference_between_event_and_command/

This page states that when comparing commands and events, we can say that: "Both are messages".

The important distinction is that commands and events are related, but different things. One is not a subclass of the other.

Commands are used to initiate an action in a system (i.e. Please do this).
Events are used to record the action in the system (i.e. I did this).

Should this page be updated to reflect the more commonly accepted categorization of these items?

**Comment by davetroiano** [comment]
addressed by PRs [262](https://github.com/confluentinc/event-streaming-patterns/pull/262) and [263](https://github.com/confluentinc/event-streaming-patterns/pull/263)

**Comment by WadeWaldron** [comment]
Thank you for these updates.
